### ISSUE TITLE
Email field is filled with 'Array'

### ISSUE THREAD

**Issue by JurriaanK** [gravitywpcom/gravitywp-gflow-save-and-continue#2]
Email field is filled with 'Array'
![image](https://user-images.githubusercontent.com/13466194/86371563-4e60ef00-bc81-11ea-9081-43cbaa9339e9.png)

field mapping:
![image](https://user-images.githubusercontent.com/13466194/86371671-78b2ac80-bc81-11ea-911e-0a47c5ef32d2.png)

This seems to be related to this lines:
\gravitywp-gflow-save-and-continue\includes\class-step-save-and-continue.php line 517 -526

These lines are not present in similar steps, like the Gravity Flow Form Connector New Entry step. What is the reason they are here?

**Comment by yoren** [comment]
@JurriaanK - I guess it's because the email field is enabled the "confirm email address" option? (not sure if it's called so but when enabling it you'll see two email inputs). I'll see if I could adress it this weekend!

**Comment by JurriaanK** [comment]
@yoren I know what you mean, but this setting isn't enabled this time. If you can have a look this weekend I appreciate it. 

Sometimes it works when we map a custom value with the mergetag of the source email-field as a workaround, but sometimes it doesn't. When I looked at the code I noticed it was different from other similar steps like 'new entry' and 'copy and delete. I found in the commit history/comments that you added these lines yourself specifically for the save and continue step:

https://github.com/gravitywpcom/gravitywp-gflow-save-and-continue/commit/81ad4fa01e02001fe2449bd84ca7a66e5f381eb0#diff-4d5d568afc35f53b55421dbc1d0851ea

There is a @todo mention in the code, but I don't understand the exact purpose, and have little time to dive into it myself at the moment, so I hoped you might know/remember ;-).
